version: "3.7"

services:
  client:
    container_name: graph_client
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    logging:
      options:
        max-size: 10m
    command: npm start -- --host 0.0.0.0 --poll 1 --proxy-config ./proxy.docker.conf.json
    networks:
      - graph
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"

  server:
    container_name: graph_server
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    logging:
      options:
        max-size: 10mb
    command: npm run start:dev -- --env=${env}
    # command: npm run start
    networks:
      - graph
    volumes:
      - ./server:/app:delegated
      - /app/node_modules
    ports:
      - "8081:8080"

networks:
  graph:
